### ISSUE TITLE
remove docs reference from a template?

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/vspk-go#4]
Right now we have a line in the `README.md` that goes like:
```
Learn how to use it from our complete documentation
```
yet the link brings you to the site where only Python VSPK is discussed. Prob, it is better to omit this statement, like in the vspk-objj

On the other hand, a good starting point would be the Bambou-Go article by Antoine https://nuagenetworks.github.io/2016/02/20/Go-Bambo-Go.html

**Comment by pdellaert** [comment]
Thanks for the suggestion, fixed it :)
