### ISSUE TITLE
Polling allalarms including root enterprise

### ISSUE THREAD

**Issue by damindaperera** [nuagenetworks/vspk-go#7]
There is a requirement to poll all types of alarms in the VSD including root enterprise level. 

func (o *Enterprise) AllAlarms(info *bambou.FetchingInfo) (AllAlarmsList, *bambou.Error) {

	var list AllAlarmsList
	err := bambou.CurrentSession().FetchChildren(o, AllAlarmIdentity, &list, info)
	return list, err
}

Used the above "AllAlarms" to retrieve the alarms. Unfortunately, root enterprise alarms were not listed. As a workaround, in order to get the root enterprise level alarms, just inserted root enterprise id into the enterprise list and let "AllAlarms" to retrieve the alarms. 

Would there be any better way to get the root enter level alarms by polling?  

enterprises, err := root.Enterprises(f)

entr := &vspk.Enterprise{
			ID: root.EnterpriseID,
		}

enterprises = append(enterprises, entr)

		for _, k := range enterprises {
			alarms, _ := k.AllAlarms(f)

**Comment by pdellaert** [comment]
Sorry @damindaperera , this seem to have been stuck in the wrong mail filter for me... Alarms are defined per enterprise, so they will have to be retrieved per enterprise.

the only other way to receive all alarms, is to use JMS or AMQP, both are offered by our VSD, more information can be found in the API Programming or API Integration guide, available in our official documentation.

**Comment by damindaperera** [comment]
@pdellaert Many thanks for the reply. You are trying to say that vspk-go is not capable to retrieve alarms at root enterprise level. Are you trying to say we need to use vspk-go to retrieve enterprise level alarms and root enterprise level alarms could be retrieved through JMS or AMQP only. As far as I see most of the alarms are generated at root enterprise level. It's important to improve the functionality of vspk API deliver this if it's not addressed already.

**Comment by pdellaert** [comment]
@damindaperera, you can still get the 'root enterprise' alarms by fetching the alarms for that enterprise... the root enterprise is still a normal enterprise, so you should be able to create the enterprise object for it, and then fetch the alarms for it...
