### ISSUE TITLE
Session url is not being properly generated.

### ISSUE THREAD

**Issue by maesoser** [nuagenetworks/vspk-go#9]
Hi,

It seems the bug fixed in "[Fixing VSPK-Go 6.0.1 with proper session URL](https://github.com/nuagenetworks/vspk-go/commit/897b68d596b47c3ed47b2deedb993957fc623f7b#diff-2b0fab1cea6874e1e0910bf2773794db)" has appeared again:

![image](https://user-images.githubusercontent.com/2486253/71248936-617f2380-231c-11ea-8724-4a89972d4ac1.png)

So I think line 65 at session.go should be changed from:

````
urlpostfix = "/" + SDKAPIPrefix + "/v" + strings.Replace(fmt.Sprintf("%.1f", SDKAPIVersion), ".", "_", 100)
````

to:
```
urlpostfix = "/" + SDKAPIPrefix + "/v" + strings.Replace(fmt.Sprintf("%.1v", SDKAPIVersion), ".", "_", 100)
```

right?

Have a nice weekend!

**Comment by pdellaert** [comment]
You are absolutely right! And the reason this happened is because I apparently fixed it directly in VSPK-go, but forgot to fix it in our tool that automatically generates VSPK-Go... Apologies for that, i'm fixing it now on both

**Comment by pdellaert** [comment]
Just added a commit that fixes this locally, and updated the tags. Thanks for bringing this up!

**Comment by maesoser** [comment]
Awesome!
